// Code generated by internal/enumgen; DO NOT EDIT.

package nhl

import (
	"encoding/json"
	"fmt"
)

// Position represents a player's position on the ice.
type Position string

const (
	// PositionCenter represents a center forward.
	PositionCenter Position = "C"
	// PositionLeftWing represents a left wing forward.
	PositionLeftWing Position = "LW"
	// PositionRightWing represents a right wing forward.
	PositionRightWing Position = "RW"
	// PositionForward represents a generic forward (used in historical data).
	PositionForward Position = "F"
	// PositionDefense represents a defenseman.
	PositionDefense Position = "D"
	// PositionGoalie represents a goaltender.
	PositionGoalie Position = "G"
)

// Code returns the position code.
func (v Position) Code() string {
	return string(v)
}

// Name returns the full name of the position.
func (v Position) Name() string {
	switch v {
	case PositionCenter:
		return "Center"
	case PositionLeftWing:
		return "Left Wing"
	case PositionRightWing:
		return "Right Wing"
	case PositionForward:
		return "Forward"
	case PositionDefense:
		return "Defense"
	case PositionGoalie:
		return "Goalie"
	default:
		return fmt.Sprintf("Unknown(%s)", string(v))
	}
}

// String returns the full name of the position.
func (v Position) String() string {
	return v.Name()
}

// IsValid returns true if the Position is one of the known valid values.
func (v Position) IsValid() bool {
	switch v {
	case PositionCenter, PositionLeftWing, PositionRightWing, PositionForward, PositionDefense, PositionGoalie:
		return true
	default:
		return false
	}
}

// PositionFromString parses a string into a Position.
// Returns an error if the string is not a valid Position.
func PositionFromString(s string) (Position, error) {
	switch s {
	case "C", "Center":
		return PositionCenter, nil
	case "L", "LW", "Left Wing", "LeftWing":
		return PositionLeftWing, nil
	case "R", "RW", "Right Wing", "RightWing":
		return PositionRightWing, nil
	case "F", "Forward":
		return PositionForward, nil
	case "D", "Defense", "Defenseman":
		return PositionDefense, nil
	case "G", "Goalie", "Goaltender":
		return PositionGoalie, nil
	default:
		return "", fmt.Errorf("invalid position: %q", s)
	}
}

// MustPositionFromString parses a string into a Position.
// Panics if the string is not a valid Position.
func MustPositionFromString(s string) Position {
	v, err := PositionFromString(s)
	if err != nil {
		panic(err)
	}
	return v
}

// UnmarshalJSON implements custom JSON unmarshaling for Position.
func (v *Position) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	parsed, err := PositionFromString(s)
	if err != nil {
		return err
	}
	*v = parsed
	return nil
}

// MarshalJSON implements custom JSON marshaling for Position.
func (v Position) MarshalJSON() ([]byte, error) {
	if !v.IsValid() {
		return nil, fmt.Errorf("cannot marshal invalid position: %q", string(v))
	}
	return json.Marshal(string(v))
}

// Handedness represents a player's shooting or catching hand.
type Handedness string

const (
	// HandednessLeft represents left-handed.
	HandednessLeft Handedness = "L"
	// HandednessRight represents right-handed.
	HandednessRight Handedness = "R"
)

// Code returns the handedness code.
func (v Handedness) Code() string {
	return string(v)
}

// Name returns the full name of the handedness.
func (v Handedness) Name() string {
	switch v {
	case HandednessLeft:
		return "Left"
	case HandednessRight:
		return "Right"
	default:
		return fmt.Sprintf("Unknown(%s)", string(v))
	}
}

// String returns the full name of the handedness.
func (v Handedness) String() string {
	return v.Name()
}

// IsValid returns true if the Handedness is one of the known valid values.
func (v Handedness) IsValid() bool {
	switch v {
	case HandednessLeft, HandednessRight:
		return true
	default:
		return false
	}
}

// HandednessFromString parses a string into a Handedness.
// Returns an error if the string is not a valid Handedness.
func HandednessFromString(s string) (Handedness, error) {
	switch s {
	case "L", "Left":
		return HandednessLeft, nil
	case "R", "Right":
		return HandednessRight, nil
	default:
		return "", fmt.Errorf("invalid handedness: %q", s)
	}
}

// MustHandednessFromString parses a string into a Handedness.
// Panics if the string is not a valid Handedness.
func MustHandednessFromString(s string) Handedness {
	v, err := HandednessFromString(s)
	if err != nil {
		panic(err)
	}
	return v
}

// UnmarshalJSON implements custom JSON unmarshaling for Handedness.
func (v *Handedness) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	if s == "" {
		*v = ""
		return nil
	}
	parsed, err := HandednessFromString(s)
	if err != nil {
		return err
	}
	*v = parsed
	return nil
}

// MarshalJSON implements custom JSON marshaling for Handedness.
func (v Handedness) MarshalJSON() ([]byte, error) {
	return json.Marshal(string(v))
}

// GoalieDecision represents the decision (result) for a goalie in a game.
type GoalieDecision string

const (
	// GoalieDecisionWin represents a win.
	GoalieDecisionWin GoalieDecision = "W"
	// GoalieDecisionLoss represents a loss.
	GoalieDecisionLoss GoalieDecision = "L"
	// GoalieDecisionTie represents a tie (used in older games).
	GoalieDecisionTie GoalieDecision = "T"
	// GoalieDecisionOvertimeLoss represents an overtime/shootout loss.
	GoalieDecisionOvertimeLoss GoalieDecision = "OTL"
)

// String returns the string representation of the GoalieDecision.
func (v GoalieDecision) String() string {
	switch v {
	case GoalieDecisionWin:
		return "Win"
	case GoalieDecisionLoss:
		return "Loss"
	case GoalieDecisionTie:
		return "Tie"
	case GoalieDecisionOvertimeLoss:
		return "Overtime Loss"
	default:
		return fmt.Sprintf("Unknown(%s)", string(v))
	}
}

// IsValid returns true if the GoalieDecision is one of the known valid values.
func (v GoalieDecision) IsValid() bool {
	switch v {
	case GoalieDecisionWin, GoalieDecisionLoss, GoalieDecisionTie, GoalieDecisionOvertimeLoss:
		return true
	default:
		return false
	}
}

// GoalieDecisionFromString parses a string into a GoalieDecision.
// Returns an error if the string is not a valid GoalieDecision.
func GoalieDecisionFromString(s string) (GoalieDecision, error) {
	switch s {
	case "W", "Win":
		return GoalieDecisionWin, nil
	case "L", "Loss":
		return GoalieDecisionLoss, nil
	case "T", "Tie":
		return GoalieDecisionTie, nil
	case "O", "OTL", "Overtime Loss", "OvertimeLoss":
		return GoalieDecisionOvertimeLoss, nil
	default:
		return "", fmt.Errorf("invalid goalie decision: %q", s)
	}
}

// MustGoalieDecisionFromString parses a string into a GoalieDecision.
// Panics if the string is not a valid GoalieDecision.
func MustGoalieDecisionFromString(s string) GoalieDecision {
	v, err := GoalieDecisionFromString(s)
	if err != nil {
		panic(err)
	}
	return v
}

// UnmarshalJSON implements custom JSON unmarshaling for GoalieDecision.
func (v *GoalieDecision) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	parsed, err := GoalieDecisionFromString(s)
	if err != nil {
		return err
	}
	*v = parsed
	return nil
}

// MarshalJSON implements custom JSON marshaling for GoalieDecision.
func (v GoalieDecision) MarshalJSON() ([]byte, error) {
	if !v.IsValid() {
		return nil, fmt.Errorf("cannot marshal invalid goalie decision: %q", string(v))
	}
	return json.Marshal(string(v))
}

// PeriodType represents the type of period in a hockey game.
type PeriodType string

const (
	// PeriodTypeRegulation represents a regulation period.
	PeriodTypeRegulation PeriodType = "REG"
	// PeriodTypeOvertime represents an overtime period.
	PeriodTypeOvertime PeriodType = "OT"
	// PeriodTypeShootout represents a shootout.
	PeriodTypeShootout PeriodType = "SO"
)

// Code returns the period type code.
func (v PeriodType) Code() string {
	return string(v)
}

// Name returns the full name of the period type.
func (v PeriodType) Name() string {
	switch v {
	case PeriodTypeRegulation:
		return "Regulation"
	case PeriodTypeOvertime:
		return "Overtime"
	case PeriodTypeShootout:
		return "Shootout"
	default:
		return fmt.Sprintf("Unknown(%s)", string(v))
	}
}

// String returns the full name of the period type.
func (v PeriodType) String() string {
	return v.Name()
}

// IsValid returns true if the PeriodType is one of the known valid values.
func (v PeriodType) IsValid() bool {
	switch v {
	case PeriodTypeRegulation, PeriodTypeOvertime, PeriodTypeShootout:
		return true
	default:
		return false
	}
}

// PeriodTypeFromString parses a string into a PeriodType.
// Returns an error if the string is not a valid PeriodType.
func PeriodTypeFromString(s string) (PeriodType, error) {
	switch s {
	case "REG", "Regulation":
		return PeriodTypeRegulation, nil
	case "OT", "Overtime":
		return PeriodTypeOvertime, nil
	case "SO", "Shootout":
		return PeriodTypeShootout, nil
	default:
		return "", fmt.Errorf("invalid period type: %q", s)
	}
}

// MustPeriodTypeFromString parses a string into a PeriodType.
// Panics if the string is not a valid PeriodType.
func MustPeriodTypeFromString(s string) PeriodType {
	v, err := PeriodTypeFromString(s)
	if err != nil {
		panic(err)
	}
	return v
}

// UnmarshalJSON implements custom JSON unmarshaling for PeriodType.
func (v *PeriodType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	parsed, err := PeriodTypeFromString(s)
	if err != nil {
		return err
	}
	*v = parsed
	return nil
}

// MarshalJSON implements custom JSON marshaling for PeriodType.
func (v PeriodType) MarshalJSON() ([]byte, error) {
	if !v.IsValid() {
		return nil, fmt.Errorf("cannot marshal invalid period type: %q", string(v))
	}
	return json.Marshal(string(v))
}

// HomeRoad represents whether a team is home or away (road).
type HomeRoad string

const (
	// HomeRoadHome represents the home team.
	HomeRoadHome HomeRoad = "H"
	// HomeRoadRoad represents the away/road team.
	HomeRoadRoad HomeRoad = "R"
)

// Code returns the home/road code.
func (v HomeRoad) Code() string {
	return string(v)
}

// Name returns the full name of the home/road.
func (v HomeRoad) Name() string {
	switch v {
	case HomeRoadHome:
		return "Home"
	case HomeRoadRoad:
		return "Road"
	default:
		return fmt.Sprintf("Unknown(%s)", string(v))
	}
}

// String returns the full name of the home/road.
func (v HomeRoad) String() string {
	return v.Name()
}

// IsValid returns true if the HomeRoad is one of the known valid values.
func (v HomeRoad) IsValid() bool {
	switch v {
	case HomeRoadHome, HomeRoadRoad:
		return true
	default:
		return false
	}
}

// HomeRoadFromString parses a string into a HomeRoad.
// Returns an error if the string is not a valid HomeRoad.
func HomeRoadFromString(s string) (HomeRoad, error) {
	switch s {
	case "H", "Home":
		return HomeRoadHome, nil
	case "R", "Road", "Away":
		return HomeRoadRoad, nil
	default:
		return "", fmt.Errorf("invalid home/road: %q", s)
	}
}

// MustHomeRoadFromString parses a string into a HomeRoad.
// Panics if the string is not a valid HomeRoad.
func MustHomeRoadFromString(s string) HomeRoad {
	v, err := HomeRoadFromString(s)
	if err != nil {
		panic(err)
	}
	return v
}

// UnmarshalJSON implements custom JSON unmarshaling for HomeRoad.
func (v *HomeRoad) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	parsed, err := HomeRoadFromString(s)
	if err != nil {
		return err
	}
	*v = parsed
	return nil
}

// MarshalJSON implements custom JSON marshaling for HomeRoad.
func (v HomeRoad) MarshalJSON() ([]byte, error) {
	if !v.IsValid() {
		return nil, fmt.Errorf("cannot marshal invalid home/road: %q", string(v))
	}
	return json.Marshal(string(v))
}

// ZoneCode represents a zone on the ice.
type ZoneCode string

const (
	// ZoneCodeOffensive represents the offensive zone.
	ZoneCodeOffensive ZoneCode = "O"
	// ZoneCodeDefensive represents the defensive zone.
	ZoneCodeDefensive ZoneCode = "D"
	// ZoneCodeNeutral represents the neutral zone.
	ZoneCodeNeutral ZoneCode = "N"
)

// Code returns the zone code code.
func (v ZoneCode) Code() string {
	return string(v)
}

// String returns the string representation of the ZoneCode.
func (v ZoneCode) String() string {
	switch v {
	case ZoneCodeOffensive:
		return "Offensive"
	case ZoneCodeDefensive:
		return "Defensive"
	case ZoneCodeNeutral:
		return "Neutral"
	default:
		return fmt.Sprintf("Unknown(%s)", string(v))
	}
}

// IsValid returns true if the ZoneCode is one of the known valid values.
func (v ZoneCode) IsValid() bool {
	switch v {
	case ZoneCodeOffensive, ZoneCodeDefensive, ZoneCodeNeutral:
		return true
	default:
		return false
	}
}

// ZoneCodeFromString parses a string into a ZoneCode.
// Returns an error if the string is not a valid ZoneCode.
func ZoneCodeFromString(s string) (ZoneCode, error) {
	switch s {
	case "O", "Offensive":
		return ZoneCodeOffensive, nil
	case "D", "Defensive":
		return ZoneCodeDefensive, nil
	case "N", "Neutral":
		return ZoneCodeNeutral, nil
	default:
		return "", fmt.Errorf("invalid zone code: %q", s)
	}
}

// MustZoneCodeFromString parses a string into a ZoneCode.
// Panics if the string is not a valid ZoneCode.
func MustZoneCodeFromString(s string) ZoneCode {
	v, err := ZoneCodeFromString(s)
	if err != nil {
		panic(err)
	}
	return v
}

// UnmarshalJSON implements custom JSON unmarshaling for ZoneCode.
func (v *ZoneCode) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	parsed, err := ZoneCodeFromString(s)
	if err != nil {
		return err
	}
	*v = parsed
	return nil
}

// MarshalJSON implements custom JSON marshaling for ZoneCode.
func (v ZoneCode) MarshalJSON() ([]byte, error) {
	if !v.IsValid() {
		return nil, fmt.Errorf("cannot marshal invalid zone code: %q", string(v))
	}
	return json.Marshal(string(v))
}

// DefendingSide represents which side of the ice a team is defending.
type DefendingSide string

const (
	// DefendingSideLeft represents defending the left side.
	DefendingSideLeft DefendingSide = "left"
	// DefendingSideRight represents defending the right side.
	DefendingSideRight DefendingSide = "right"
)

// String returns the string representation of the DefendingSide.
func (v DefendingSide) String() string {
	return string(v)
}

// IsValid returns true if the DefendingSide is one of the known valid values.
func (v DefendingSide) IsValid() bool {
	switch v {
	case DefendingSideLeft, DefendingSideRight:
		return true
	default:
		return false
	}
}

// DefendingSideFromString parses a string into a DefendingSide.
// Returns an error if the string is not a valid DefendingSide.
func DefendingSideFromString(s string) (DefendingSide, error) {
	switch s {
	case "left":
		return DefendingSideLeft, nil
	case "right":
		return DefendingSideRight, nil
	default:
		return "", fmt.Errorf("invalid defending side: %q", s)
	}
}

// MustDefendingSideFromString parses a string into a DefendingSide.
// Panics if the string is not a valid DefendingSide.
func MustDefendingSideFromString(s string) DefendingSide {
	v, err := DefendingSideFromString(s)
	if err != nil {
		panic(err)
	}
	return v
}

// UnmarshalJSON implements custom JSON unmarshaling for DefendingSide.
func (v *DefendingSide) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	if s == "" {
		*v = ""
		return nil
	}
	parsed, err := DefendingSideFromString(s)
	if err != nil {
		return err
	}
	*v = parsed
	return nil
}

// MarshalJSON implements custom JSON marshaling for DefendingSide.
func (v DefendingSide) MarshalJSON() ([]byte, error) {
	if v == "" {
		return json.Marshal("")
	}
	if !v.IsValid() {
		return nil, fmt.Errorf("cannot marshal invalid defending side: %q", string(v))
	}
	return json.Marshal(string(v))
}

// GameScheduleState represents the state of a scheduled game.
type GameScheduleState string

const (
	// GameScheduleStateOK represents a normal scheduled game.
	GameScheduleStateOK GameScheduleState = "OK"
	// GameScheduleStateDontPlay represents a game that won't be played.
	GameScheduleStateDontPlay GameScheduleState = "DONT_PLAY"
	// GameScheduleStatePostponed represents a postponed game.
	GameScheduleStatePostponed GameScheduleState = "PPD"
	// GameScheduleStateSuspended represents a suspended game.
	GameScheduleStateSuspended GameScheduleState = "SUSP"
	// GameScheduleStateTBD represents a game with time to be determined.
	GameScheduleStateTBD GameScheduleState = "TBD"
	// GameScheduleStateCompleted represents a completed game.
	GameScheduleStateCompleted GameScheduleState = "COMPLETED"
	// GameScheduleStateCancelled represents a cancelled game.
	GameScheduleStateCancelled GameScheduleState = "CNCL"
)

// String returns the string representation of the GameScheduleState.
func (v GameScheduleState) String() string {
	return string(v)
}

// IsValid returns true if the GameScheduleState is one of the known valid values.
func (v GameScheduleState) IsValid() bool {
	switch v {
	case GameScheduleStateOK, GameScheduleStateDontPlay, GameScheduleStatePostponed, GameScheduleStateSuspended, GameScheduleStateTBD, GameScheduleStateCompleted, GameScheduleStateCancelled:
		return true
	default:
		return false
	}
}

// GameScheduleStateFromString parses a string into a GameScheduleState.
// Returns an error if the string is not a valid GameScheduleState.
func GameScheduleStateFromString(s string) (GameScheduleState, error) {
	v := GameScheduleState(s)
	if !v.IsValid() {
		return "", fmt.Errorf("invalid game schedule state: %q", s)
	}
	return v, nil
}

// MustGameScheduleStateFromString parses a string into a GameScheduleState.
// Panics if the string is not a valid GameScheduleState.
func MustGameScheduleStateFromString(s string) GameScheduleState {
	v, err := GameScheduleStateFromString(s)
	if err != nil {
		panic(err)
	}
	return v
}

// UnmarshalJSON implements custom JSON unmarshaling for GameScheduleState.
func (v *GameScheduleState) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	parsed, err := GameScheduleStateFromString(s)
	if err != nil {
		return err
	}
	*v = parsed
	return nil
}

// MarshalJSON implements custom JSON marshaling for GameScheduleState.
func (v GameScheduleState) MarshalJSON() ([]byte, error) {
	if !v.IsValid() {
		return nil, fmt.Errorf("cannot marshal invalid game schedule state: %q", string(v))
	}
	return json.Marshal(string(v))
}

// PlayEventType represents a type of play event during a game.
type PlayEventType string

const (
	// PlayEventTypeGameStart represents the start of a game.
	PlayEventTypeGameStart PlayEventType = "game-start"
	// PlayEventTypePeriodStart represents the start of a period.
	PlayEventTypePeriodStart PlayEventType = "period-start"
	// PlayEventTypePeriodEnd represents the end of a period.
	PlayEventTypePeriodEnd PlayEventType = "period-end"
	// PlayEventTypeGameEnd represents the end of a game.
	PlayEventTypeGameEnd PlayEventType = "game-end"
	// PlayEventTypeFaceoff represents a faceoff.
	PlayEventTypeFaceoff PlayEventType = "faceoff"
	// PlayEventTypeHit represents a hit.
	PlayEventTypeHit PlayEventType = "hit"
	// PlayEventTypeGiveaway represents a giveaway.
	PlayEventTypeGiveaway PlayEventType = "giveaway"
	// PlayEventTypeTakeaway represents a takeaway.
	PlayEventTypeTakeaway PlayEventType = "takeaway"
	// PlayEventTypeShotOnGoal represents a shot on goal.
	PlayEventTypeShotOnGoal PlayEventType = "shot-on-goal"
	// PlayEventTypeMissedShot represents a missed shot.
	PlayEventTypeMissedShot PlayEventType = "missed-shot"
	// PlayEventTypeBlockedShot represents a blocked shot.
	PlayEventTypeBlockedShot PlayEventType = "blocked-shot"
	// PlayEventTypeGoal represents a goal.
	PlayEventTypeGoal PlayEventType = "goal"
	// PlayEventTypePenalty represents a penalty.
	PlayEventTypePenalty PlayEventType = "penalty"
	// PlayEventTypeStoppage represents a stoppage in play.
	PlayEventTypeStoppage PlayEventType = "stoppage"
	// PlayEventTypeDelayedPenalty represents a delayed penalty.
	PlayEventTypeDelayedPenalty PlayEventType = "delayed-penalty"
	// PlayEventTypeFailedShotAttempt represents a failed shot attempt.
	PlayEventTypeFailedShotAttempt PlayEventType = "failed-shot-attempt"
	// PlayEventTypeShootoutComplete represents the completion of a shootout.
	PlayEventTypeShootoutComplete PlayEventType = "shootout-complete"
	// PlayEventTypeUnknown represents an unknown event type.
	PlayEventTypeUnknown PlayEventType = "unknown"
)

// String returns the string representation of the PlayEventType.
func (v PlayEventType) String() string {
	return string(v)
}

// IsValid returns true if the PlayEventType is one of the known valid values.
func (v PlayEventType) IsValid() bool {
	switch v {
	case PlayEventTypeGameStart, PlayEventTypePeriodStart, PlayEventTypePeriodEnd, PlayEventTypeGameEnd, PlayEventTypeFaceoff, PlayEventTypeHit, PlayEventTypeGiveaway, PlayEventTypeTakeaway, PlayEventTypeShotOnGoal, PlayEventTypeMissedShot, PlayEventTypeBlockedShot, PlayEventTypeGoal, PlayEventTypePenalty, PlayEventTypeStoppage, PlayEventTypeDelayedPenalty, PlayEventTypeFailedShotAttempt, PlayEventTypeShootoutComplete, PlayEventTypeUnknown:
		return true
	default:
		return false
	}
}

// PlayEventTypeFromString parses a string into a PlayEventType.
// Returns an error if the string is not a valid PlayEventType.
func PlayEventTypeFromString(s string) (PlayEventType, error) {
	v := PlayEventType(s)
	if !v.IsValid() {
		return "", fmt.Errorf("invalid play event type: %q", s)
	}
	return v, nil
}

// MustPlayEventTypeFromString parses a string into a PlayEventType.
// Panics if the string is not a valid PlayEventType.
func MustPlayEventTypeFromString(s string) PlayEventType {
	v, err := PlayEventTypeFromString(s)
	if err != nil {
		panic(err)
	}
	return v
}

// UnmarshalJSON implements custom JSON unmarshaling for PlayEventType.
func (v *PlayEventType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	parsed, err := PlayEventTypeFromString(s)
	if err != nil {
		return err
	}
	*v = parsed
	return nil
}

// MarshalJSON implements custom JSON marshaling for PlayEventType.
func (v PlayEventType) MarshalJSON() ([]byte, error) {
	if !v.IsValid() {
		return nil, fmt.Errorf("cannot marshal invalid play event type: %q", string(v))
	}
	return json.Marshal(string(v))
}

// GameState represents the current state of an NHL game.
type GameState string

const (
	// GameStateFuture represents a game that has not yet started.
	GameStateFuture GameState = "FUT"
	// GameStatePreGame represents a game in pre-game state.
	GameStatePreGame GameState = "PRE"
	// GameStateLive represents a game currently in progress.
	GameStateLive GameState = "LIVE"
	// GameStateFinal represents a completed game.
	GameStateFinal GameState = "FINAL"
	// GameStateOff represents a game that is off/completed (alternative to FINAL).
	GameStateOff GameState = "OFF"
	// GameStatePostponed represents a postponed game.
	GameStatePostponed GameState = "PPD"
	// GameStateSuspended represents a suspended game.
	GameStateSuspended GameState = "SUSP"
	// GameStateCritical represents a game in critical state.
	GameStateCritical GameState = "CRIT"
)

// String returns the string representation of the GameState.
func (v GameState) String() string {
	return string(v)
}

// IsValid returns true if the GameState is one of the known valid values.
func (v GameState) IsValid() bool {
	switch v {
	case GameStateFuture, GameStatePreGame, GameStateLive, GameStateFinal, GameStateOff, GameStatePostponed, GameStateSuspended, GameStateCritical:
		return true
	default:
		return false
	}
}

// GameStateFromString parses a string into a GameState.
// Returns an error if the string is not a valid GameState.
func GameStateFromString(s string) (GameState, error) {
	v := GameState(s)
	if !v.IsValid() {
		return "", fmt.Errorf("invalid game state: %q", s)
	}
	return v, nil
}

// MustGameStateFromString parses a string into a GameState.
// Panics if the string is not a valid GameState.
func MustGameStateFromString(s string) GameState {
	v, err := GameStateFromString(s)
	if err != nil {
		panic(err)
	}
	return v
}

// UnmarshalJSON implements custom JSON unmarshaling for GameState.
func (v *GameState) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	parsed, err := GameStateFromString(s)
	if err != nil {
		return err
	}
	*v = parsed
	return nil
}

// MarshalJSON implements custom JSON marshaling for GameState.
func (v GameState) MarshalJSON() ([]byte, error) {
	if !v.IsValid() {
		return nil, fmt.Errorf("cannot marshal invalid game state: %q", string(v))
	}
	return json.Marshal(string(v))
}
