// Code generated by internal/idgen; DO NOT EDIT.

package nhl

import (
	"encoding/json"
	"strconv"
)

// GameID is a wrapper type for NHL game identifiers.
// Game IDs are 10-digit integers in the format: SSSGTNNNN where:
// - SSS is the first 4 digits of the season (e.g., 2023 for 2023-2024)
// - GT is the game type (01=preseason, 02=regular, 03=playoffs, 04=all-star, 12=PWHL showcase)
// - NNNN is the game number
type GameID int64

// NewGameID creates a new GameID from an int64.
func NewGameID(id int64) GameID { return GameID(id) }

// Int64 returns the GameID as an int64.
func (g GameID) Int64() int64 { return int64(g) }

// String implements the fmt.Stringer interface.
func (g GameID) String() string { return strconv.FormatInt(int64(g), 10) }

// MarshalJSON implements json.Marshaler.
// GameIDs are marshaled as integers in JSON.
func (g GameID) MarshalJSON() ([]byte, error) { return json.Marshal(int64(g)) }

// UnmarshalJSON implements json.Unmarshaler.
// GameIDs can be unmarshaled from either integers or strings.
func (g *GameID) UnmarshalJSON(data []byte) error {
	i, err := unmarshalNumericID(data, "game ID")
	if err != nil {
		return err
	}
	*g = GameID(i)
	return nil
}

// GameIDFromInt creates a GameID from an int.
func GameIDFromInt(i int) GameID { return GameID(i) }

// GameIDFromString parses a GameID from a string.
func GameIDFromString(s string) (GameID, error) {
	i, err := parseNumericID(s, "game ID")
	if err != nil {
		return 0, err
	}
	return GameID(i), nil
}

// MustGameIDFromString parses a GameID from a string and panics on error.
func MustGameIDFromString(s string) GameID {
	id, err := GameIDFromString(s)
	if err != nil {
		panic(err)
	}
	return id
}

// PlayerID is a wrapper type for NHL player identifiers.
// Player IDs are numeric identifiers assigned to each player (e.g., 8478402 for Connor McDavid).
type PlayerID int64

// NewPlayerID creates a new PlayerID from an int64.
func NewPlayerID(id int64) PlayerID { return PlayerID(id) }

// Int64 returns the PlayerID as an int64.
func (p PlayerID) Int64() int64 { return int64(p) }

// String implements the fmt.Stringer interface.
func (p PlayerID) String() string { return strconv.FormatInt(int64(p), 10) }

// MarshalJSON implements json.Marshaler.
// PlayerIDs are marshaled as integers in JSON.
func (p PlayerID) MarshalJSON() ([]byte, error) { return json.Marshal(int64(p)) }

// UnmarshalJSON implements json.Unmarshaler.
// PlayerIDs can be unmarshaled from either integers or strings.
func (p *PlayerID) UnmarshalJSON(data []byte) error {
	i, err := unmarshalNumericID(data, "player ID")
	if err != nil {
		return err
	}
	*p = PlayerID(i)
	return nil
}

// PlayerIDFromInt creates a PlayerID from an int.
func PlayerIDFromInt(i int) PlayerID { return PlayerID(i) }

// PlayerIDFromString parses a PlayerID from a string.
func PlayerIDFromString(s string) (PlayerID, error) {
	i, err := parseNumericID(s, "player ID")
	if err != nil {
		return 0, err
	}
	return PlayerID(i), nil
}

// MustPlayerIDFromString parses a PlayerID from a string and panics on error.
func MustPlayerIDFromString(s string) PlayerID {
	id, err := PlayerIDFromString(s)
	if err != nil {
		panic(err)
	}
	return id
}

// TeamID is a wrapper type for NHL team identifiers.
// Team IDs are numeric identifiers assigned to each team (e.g., 10 for Toronto Maple Leafs).
type TeamID int64

// NewTeamID creates a new TeamID from an int64.
func NewTeamID(id int64) TeamID { return TeamID(id) }

// Int64 returns the TeamID as an int64.
func (t TeamID) Int64() int64 { return int64(t) }

// String implements the fmt.Stringer interface.
func (t TeamID) String() string { return strconv.FormatInt(int64(t), 10) }

// MarshalJSON implements json.Marshaler.
// TeamIDs are marshaled as integers in JSON.
func (t TeamID) MarshalJSON() ([]byte, error) { return json.Marshal(int64(t)) }

// UnmarshalJSON implements json.Unmarshaler.
// TeamIDs can be unmarshaled from either integers or strings.
func (t *TeamID) UnmarshalJSON(data []byte) error {
	i, err := unmarshalNumericID(data, "team ID")
	if err != nil {
		return err
	}
	*t = TeamID(i)
	return nil
}

// TeamIDFromInt creates a TeamID from an int.
func TeamIDFromInt(i int) TeamID { return TeamID(i) }

// TeamIDFromString parses a TeamID from a string.
func TeamIDFromString(s string) (TeamID, error) {
	i, err := parseNumericID(s, "team ID")
	if err != nil {
		return 0, err
	}
	return TeamID(i), nil
}

// MustTeamIDFromString parses a TeamID from a string and panics on error.
func MustTeamIDFromString(s string) TeamID {
	id, err := TeamIDFromString(s)
	if err != nil {
		panic(err)
	}
	return id
}
