// idgen generates boilerplate methods for numeric ID wrapper types.
//
// It produces: type declaration, NewXxx constructor, Int64(), String(),
// MarshalJSON(), UnmarshalJSON(), XxxFromInt(), XxxFromString(), MustXxxFromString().
//
// The generated file is written to ids_generated.go in the current directory,
// which must be the nhl/ package directory when invoked via go:generate.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
)

func main() {
	var buf bytes.Buffer

	writeHeader(&buf)
	for _, id := range ids {
		writeID(&buf, id)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Write unformatted for debugging
		os.WriteFile("ids_generated.go", buf.Bytes(), 0644)
		log.Fatalf("gofmt failed (wrote unformatted output for debugging): %v", err)
	}

	if err := os.WriteFile("ids_generated.go", formatted, 0644); err != nil {
		log.Fatalf("write ids_generated.go: %v", err)
	}
}

func writeHeader(w *bytes.Buffer) {
	fmt.Fprintf(w, "// Code generated by internal/idgen; DO NOT EDIT.\n\n")
	fmt.Fprintf(w, "package nhl\n\n")
	fmt.Fprintf(w, "import (\n")
	fmt.Fprintf(w, "\t\"encoding/json\"\n")
	fmt.Fprintf(w, "\t\"strconv\"\n")
	fmt.Fprintf(w, ")\n\n")
}

func writeID(w *bytes.Buffer, id IDDef) {
	r := id.Receiver
	t := id.TypeName

	// Type declaration
	fmt.Fprintf(w, "// %s\n", id.Doc)
	fmt.Fprintf(w, "type %s int64\n\n", t)

	// NewXxx constructor
	fmt.Fprintf(w, "// New%s creates a new %s from an int64.\n", t, t)
	fmt.Fprintf(w, "func New%s(id int64) %s { return %s(id) }\n\n", t, t, t)

	// Int64()
	fmt.Fprintf(w, "// Int64 returns the %s as an int64.\n", t)
	fmt.Fprintf(w, "func (%s %s) Int64() int64 { return int64(%s) }\n\n", r, t, r)

	// String()
	fmt.Fprintf(w, "// String implements the fmt.Stringer interface.\n")
	fmt.Fprintf(w, "func (%s %s) String() string { return strconv.FormatInt(int64(%s), 10) }\n\n", r, t, r)

	// MarshalJSON()
	fmt.Fprintf(w, "// MarshalJSON implements json.Marshaler.\n")
	fmt.Fprintf(w, "// %ss are marshaled as integers in JSON.\n", t)
	fmt.Fprintf(w, "func (%s %s) MarshalJSON() ([]byte, error) { return json.Marshal(int64(%s)) }\n\n", r, t, r)

	// UnmarshalJSON()
	fmt.Fprintf(w, "// UnmarshalJSON implements json.Unmarshaler.\n")
	fmt.Fprintf(w, "// %ss can be unmarshaled from either integers or strings.\n", t)
	fmt.Fprintf(w, "func (%s *%s) UnmarshalJSON(data []byte) error {\n", r, t)
	fmt.Fprintf(w, "\ti, err := unmarshalNumericID(data, %q)\n", id.ErrorLabel)
	fmt.Fprintf(w, "\tif err != nil {\n\t\treturn err\n\t}\n")
	fmt.Fprintf(w, "\t*%s = %s(i)\n", r, t)
	fmt.Fprintf(w, "\treturn nil\n")
	fmt.Fprintf(w, "}\n\n")

	// XxxFromInt()
	fmt.Fprintf(w, "// %sFromInt creates a %s from an int.\n", t, t)
	fmt.Fprintf(w, "func %sFromInt(i int) %s { return %s(i) }\n\n", t, t, t)

	// XxxFromString()
	fmt.Fprintf(w, "// %sFromString parses a %s from a string.\n", t, t)
	fmt.Fprintf(w, "func %sFromString(s string) (%s, error) {\n", t, t)
	fmt.Fprintf(w, "\ti, err := parseNumericID(s, %q)\n", id.ErrorLabel)
	fmt.Fprintf(w, "\tif err != nil {\n\t\treturn 0, err\n\t}\n")
	fmt.Fprintf(w, "\treturn %s(i), nil\n", t)
	fmt.Fprintf(w, "}\n\n")

	// MustXxxFromString()
	fmt.Fprintf(w, "// Must%sFromString parses a %s from a string and panics on error.\n", t, t)
	fmt.Fprintf(w, "func Must%sFromString(s string) %s {\n", t, t)
	fmt.Fprintf(w, "\tid, err := %sFromString(s)\n", t)
	fmt.Fprintf(w, "\tif err != nil {\n\t\tpanic(err)\n\t}\n")
	fmt.Fprintf(w, "\treturn id\n")
	fmt.Fprintf(w, "}\n\n")
}
