// enumgen generates boilerplate methods for string-based enum types.
//
// It produces: type declaration, constants, String(), Code(), Name(),
// IsValid(), FromString(), MustFromString(), UnmarshalJSON(), MarshalJSON().
//
// Custom domain methods (e.g., IsForward, IsOvertime) are hand-written
// in separate files and are not touched by this generator.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
)

func main() {
	var buf bytes.Buffer

	writeHeader(&buf)
	for _, e := range enums {
		writeEnum(&buf, e)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Write unformatted for debugging
		os.WriteFile("enums_generated.go", buf.Bytes(), 0644)
		log.Fatalf("gofmt failed (wrote unformatted output for debugging): %v", err)
	}

	if err := os.WriteFile("enums_generated.go", formatted, 0644); err != nil {
		log.Fatalf("write enums_generated.go: %v", err)
	}
}

func writeHeader(w *bytes.Buffer) {
	fmt.Fprintf(w, "// Code generated by internal/enumgen; DO NOT EDIT.\n\n")
	fmt.Fprintf(w, "package nhl\n\n")
	fmt.Fprintf(w, "import (\n")
	fmt.Fprintf(w, "\t\"encoding/json\"\n")
	fmt.Fprintf(w, "\t\"fmt\"\n")
	fmt.Fprintf(w, ")\n\n")
}

func writeEnum(w *bytes.Buffer, e EnumDef) {
	// Type declaration
	fmt.Fprintf(w, "// %s\n", e.Doc)
	fmt.Fprintf(w, "type %s string\n\n", e.TypeName)

	// Const block
	fmt.Fprintf(w, "const (\n")
	for _, v := range e.Values {
		fmt.Fprintf(w, "\t// %s\n", v.Doc)
		fmt.Fprintf(w, "\t%s %s = %q\n", v.Name, e.TypeName, v.Value)
	}
	fmt.Fprintf(w, ")\n\n")

	// Code() method
	if e.HasCode {
		fmt.Fprintf(w, "// Code returns the %s code.\n", e.ErrorLabel)
		fmt.Fprintf(w, "func (v %s) Code() string {\n", e.TypeName)
		fmt.Fprintf(w, "\treturn string(v)\n")
		fmt.Fprintf(w, "}\n\n")
	}

	// Name() and String() methods
	if e.HasName {
		// Name() with display name switch
		fmt.Fprintf(w, "// Name returns the full name of the %s.\n", e.ErrorLabel)
		fmt.Fprintf(w, "func (v %s) Name() string {\n", e.TypeName)
		fmt.Fprintf(w, "\tswitch v {\n")
		for _, v := range e.Values {
			fmt.Fprintf(w, "\tcase %s:\n\t\treturn %q\n", v.Name, v.DisplayName)
		}
		fmt.Fprintf(w, "\tdefault:\n\t\treturn fmt.Sprintf(\"Unknown(%%s)\", string(v))\n")
		fmt.Fprintf(w, "\t}\n}\n\n")

		// String() delegates to Name()
		fmt.Fprintf(w, "// String returns the full name of the %s.\n", e.ErrorLabel)
		fmt.Fprintf(w, "func (v %s) String() string {\n", e.TypeName)
		fmt.Fprintf(w, "\treturn v.Name()\n")
		fmt.Fprintf(w, "}\n\n")
	} else if e.HasDisplayName {
		// String() with display name switch (no separate Name method)
		fmt.Fprintf(w, "// String returns the string representation of the %s.\n", e.TypeName)
		fmt.Fprintf(w, "func (v %s) String() string {\n", e.TypeName)
		fmt.Fprintf(w, "\tswitch v {\n")
		for _, v := range e.Values {
			fmt.Fprintf(w, "\tcase %s:\n\t\treturn %q\n", v.Name, v.DisplayName)
		}
		fmt.Fprintf(w, "\tdefault:\n\t\treturn fmt.Sprintf(\"Unknown(%%s)\", string(v))\n")
		fmt.Fprintf(w, "\t}\n}\n\n")
	} else {
		// String() returns raw underlying value
		fmt.Fprintf(w, "// String returns the string representation of the %s.\n", e.TypeName)
		fmt.Fprintf(w, "func (v %s) String() string {\n", e.TypeName)
		fmt.Fprintf(w, "\treturn string(v)\n")
		fmt.Fprintf(w, "}\n\n")
	}

	// IsValid()
	fmt.Fprintf(w, "// IsValid returns true if the %s is one of the known valid values.\n", e.TypeName)
	fmt.Fprintf(w, "func (v %s) IsValid() bool {\n", e.TypeName)
	fmt.Fprintf(w, "\tswitch v {\n")
	fmt.Fprintf(w, "\tcase ")
	for i, v := range e.Values {
		if i > 0 {
			fmt.Fprintf(w, ", ")
		}
		fmt.Fprintf(w, "%s", v.Name)
	}
	fmt.Fprintf(w, ":\n\t\treturn true\n")
	fmt.Fprintf(w, "\tdefault:\n\t\treturn false\n")
	fmt.Fprintf(w, "\t}\n}\n\n")

	// FromString()
	fmt.Fprintf(w, "// %sFromString parses a string into a %s.\n", e.TypeName, e.TypeName)
	fmt.Fprintf(w, "// Returns an error if the string is not a valid %s.\n", e.TypeName)
	fmt.Fprintf(w, "func %sFromString(s string) (%s, error) {\n", e.TypeName, e.TypeName)
	if e.HasAliases() {
		fmt.Fprintf(w, "\tswitch s {\n")
		for _, v := range e.Values {
			fmt.Fprintf(w, "\tcase ")
			for i, a := range v.Aliases {
				if i > 0 {
					fmt.Fprintf(w, ", ")
				}
				fmt.Fprintf(w, "%q", a)
			}
			fmt.Fprintf(w, ":\n\t\treturn %s, nil\n", v.Name)
		}
		fmt.Fprintf(w, "\tdefault:\n\t\treturn \"\", fmt.Errorf(\"invalid %s: %%q\", s)\n", e.ErrorLabel)
		fmt.Fprintf(w, "\t}\n")
	} else {
		fmt.Fprintf(w, "\tv := %s(s)\n", e.TypeName)
		fmt.Fprintf(w, "\tif !v.IsValid() {\n")
		fmt.Fprintf(w, "\t\treturn \"\", fmt.Errorf(\"invalid %s: %%q\", s)\n", e.ErrorLabel)
		fmt.Fprintf(w, "\t}\n")
		fmt.Fprintf(w, "\treturn v, nil\n")
	}
	fmt.Fprintf(w, "}\n\n")

	// MustFromString()
	fmt.Fprintf(w, "// Must%sFromString parses a string into a %s.\n", e.TypeName, e.TypeName)
	fmt.Fprintf(w, "// Panics if the string is not a valid %s.\n", e.TypeName)
	fmt.Fprintf(w, "func Must%sFromString(s string) %s {\n", e.TypeName, e.TypeName)
	fmt.Fprintf(w, "\tv, err := %sFromString(s)\n", e.TypeName)
	fmt.Fprintf(w, "\tif err != nil {\n\t\tpanic(err)\n\t}\n")
	fmt.Fprintf(w, "\treturn v\n")
	fmt.Fprintf(w, "}\n\n")

	// UnmarshalJSON()
	fmt.Fprintf(w, "// UnmarshalJSON implements custom JSON unmarshaling for %s.\n", e.TypeName)
	fmt.Fprintf(w, "func (v *%s) UnmarshalJSON(data []byte) error {\n", e.TypeName)
	fmt.Fprintf(w, "\tvar s string\n")
	fmt.Fprintf(w, "\tif err := json.Unmarshal(data, &s); err != nil {\n\t\treturn err\n\t}\n")
	if e.AllowEmpty {
		fmt.Fprintf(w, "\tif s == \"\" {\n\t\t*v = \"\"\n\t\treturn nil\n\t}\n")
	}
	fmt.Fprintf(w, "\tparsed, err := %sFromString(s)\n", e.TypeName)
	fmt.Fprintf(w, "\tif err != nil {\n\t\treturn err\n\t}\n")
	fmt.Fprintf(w, "\t*v = parsed\n")
	fmt.Fprintf(w, "\treturn nil\n")
	fmt.Fprintf(w, "}\n\n")

	// MarshalJSON()
	fmt.Fprintf(w, "// MarshalJSON implements custom JSON marshaling for %s.\n", e.TypeName)
	fmt.Fprintf(w, "func (v %s) MarshalJSON() ([]byte, error) {\n", e.TypeName)
	if e.SkipMarshalValidation {
		fmt.Fprintf(w, "\treturn json.Marshal(string(v))\n")
	} else if e.AllowEmpty {
		fmt.Fprintf(w, "\tif v == \"\" {\n\t\treturn json.Marshal(\"\")\n\t}\n")
		fmt.Fprintf(w, "\tif !v.IsValid() {\n\t\treturn nil, fmt.Errorf(\"cannot marshal invalid %s: %%q\", string(v))\n\t}\n", e.ErrorLabel)
		fmt.Fprintf(w, "\treturn json.Marshal(string(v))\n")
	} else {
		fmt.Fprintf(w, "\tif !v.IsValid() {\n\t\treturn nil, fmt.Errorf(\"cannot marshal invalid %s: %%q\", string(v))\n\t}\n", e.ErrorLabel)
		fmt.Fprintf(w, "\treturn json.Marshal(string(v))\n")
	}
	fmt.Fprintf(w, "}\n\n")
}
